[platformio]
default_envs = esp32dev
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<esp32_microphone.ino>
  +<src/*.cpp>
build_flags =
  -DEIDSP_QUANTIZE_FILTERBANK=0
lib_ldf_mode = deep+
lib_deps =
  bblanchon/ArduinoJson@7.4.2
  sinricpro/SinricPro@3.5.2
  links2004/WebSockets@2.7.1
